waterius:
  mqtt:
    sensor:
      # waterius в ванной


      - name: "waterius Bathroom Cold Water"
        unique_id: waterius_bcwm
        state_topic: "waterius/1295260/ch1"
        value_template: "{{ value }}"
        state_class: measurement
        unit_of_measurement: "m³"
        icon: mdi:water

      - name: "waterius Bathroom Hot Water"
        unique_id: waterius_bhwm
        state_topic: "waterius/1295260/ch0"
        value_template: "{{ value }}"
        state_class: measurement
        unit_of_measurement: "m³"
        icon: mdi:water

      - name: "waterius Bathroom Cold Day"
        unique_id: waterius_bcwd
        state_topic: "waterius/1295260/delta1"
        value_template: "{{ value }}"
        state_class: measurement
        unit_of_measurement: "литр"
        icon: mdi:delta

      - name: "waterius Bathroom Hot Day"
        unique_id: waterius_bhwd
        state_topic: "waterius/1295260/delta0"
        value_template: "{{ value }}"
        state_class: measurement
        unit_of_measurement: "литр"
        icon: mdi:delta

      - name: "waterius Bathroom Voltage"
        unique_id: waterius_bv
        state_topic: "waterius/1295260/voltage"
        value_template: "{{ value }}"
        unit_of_measurement: "V"
        icon: mdi:battery


# вспомогательные сенсоры
      - name: "waterius Количество импульсов Холодная"
        unique_id: waterius_imp1
        state_topic: "waterius/1295260/imp1"
        value_template: "{{ value }}"
        unit_of_measurement: "шт"
        # icon: mdi:battery

      - name: "waterius Количество импульсов Горячая"
        unique_id: waterius_imp0
        state_topic: "waterius/1295260/imp0"
        value_template: "{{ value }}"
        unit_of_measurement: "шт"
        # icon: mdi:battery

      - name: "waterius Аналоговый уровень входа 0"
        unique_id: waterius_adc0
        state_topic: "waterius/1295260/adc0"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius Аналоговый уровень входа 1"
        unique_id: waterius_adc1
        state_topic: "waterius/1295260/adc1"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius good"
        unique_id: waterius_good
        state_topic: "waterius/1295260/good"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius boot"
        unique_id: waterius_boot
        state_topic: "waterius/1295260/boot"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius version"
        unique_id: waterius_version
        state_topic: "waterius/1295260/version"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius version esp"
        unique_id: waterius_version_esp
        state_topic: "waterius/1295260/version_esp"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius key"
        unique_id: waterius_key
        state_topic: "waterius/1295260/key"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius resets"
        unique_id: waterius_resets
        state_topic: "waterius/1295260/resets"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius voltage_diff"
        unique_id: waterius_voltage_diff
        state_topic: "waterius/1295260/voltage_diff"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius rssi"
        unique_id: waterius_rssi
        state_topic: "waterius/1295260/rssi"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius waketime"
        unique_id: waterius_waketime
        state_topic: "waterius/1295260/waketime"
        value_template: "{{ value }}"
        # icon: mdi:battery



      - name: "waterius period_min"
        unique_id: waterius_period_min
        state_topic: "waterius/1295260/period_min"
        value_template: "{{ value }}"
        # icon: mdi:battery

      - name: "waterius mode"
        unique_id: waterius_mode
        state_topic: "waterius/1295260/mode"
        value_template: > 
          {%if value == 2 %}
            'Авто'
          {% else %}
            'По кнопке'
          {% endif %}

        # Создаём сенсор низкого напряжения питания Ватериуса, для последующего использования в автоматизациях
      - name: 'waterius Напряжение '
        unique_id: waterius_vlow
        state_topic: 'waterius/1295260/voltage_low'
        value_template: > 
          {%if value == 1 %}
            'Низкое напряжение'
          {% else %}
            'Напряжение в порядке'
          {% endif %}

# этот конфиг устарел и не будет работать с 2022.12
  # sensor:
      # # Создаём сенсор счётчик прошедшего времени с момента последнего обновления данных Ватериусом
      # # Используем время последнего обновления показаний холодной воды, так как этот сенсор обновляется
      # # чаще, чем все остальные

    # - platform: template
      # sensors:
          # waterius_last_seen:
            # friendly_name: 'Ватериус вне сети'
            # value_template: >
               # {%- set time = (as_timestamp(now())-as_timestamp(states.sensor.waterius_bathroom_cold_water.last_updated))|int %}
               # {%- set minutes = ((time % 3600) // 60) %}
               # {%- set minutes = '{} мин.'.format(minutes) if minutes > 0 else '' %}
               # {%- set hours = ((time % 86400) // 3600) %}
               # {%- set hours = '{} ч. '.format(hours) if hours > 0 else '' %}
               # {%- set days = (time // 86400) %}
               # {%- set days = '{} д. '.format(days) if days > 0 else '' %}
               # {{ 'Меньше минуты' if time < 60 else days + hours + minutes }}
    # # - platform: template
      # # sensors:
          # waterius_last_update:
            # friendly_name: 'Последнее обновление показаний'   
            # value_template: >
                 # {{ as_timestamp(states.sensor.waterius_bathroom_cold_water.last_updated)|timestamp_custom('%d-%m-%Y %H:%M:%S')   }}

  template:
    - sensor:
      - name: "waterius last seen"
        unique_id: waterius_last_seen
        state: >
           {%- set time = (as_timestamp(now())-as_timestamp(states.sensor.waterius_bathroom_cold_water.last_updated))|int %}
           {%- set minutes = ((time % 3600) // 60) %}
           {%- set minutes = '{} мин.'.format(minutes) if minutes > 0 else '' %}
           {%- set hours = ((time % 86400) // 3600) %}
           {%- set hours = '{} ч. '.format(hours) if hours > 0 else '' %}
           {%- set days = (time // 86400) %}
           {%- set days = '{} д. '.format(days) if days > 0 else '' %}
           {{ 'Меньше минуты' if time < 60 else days + hours + minutes }}

      - name: "waterius last update"
        unique_id: waterius_last_update
        state: >
             {{ as_timestamp(states.sensor.waterius_bathroom_cold_water.last_updated)|timestamp_custom('%d-%m-%Y %H:%M:%S')   }}




      - name: "Waterius Cold water m3"
        unique_id: waterius_cold_water_m3
        unit_of_measurement: "m³"
        state_class: total_increasing
        device_class: water
        icon: mdi:water-outline
        availability: >
          {{ not states('sensor.waterius_kolichestvo_impulsov_kholodnaia') in ['unavailable', 'unknown'] }}
        state: >
          {% if not states('sensor.waterius_kolichestvo_impulsov_kholodnaia') in ['unavailable', 'unknown'] %}
            {{ states('sensor.waterius_kolichestvo_impulsov_kholodnaia') | int(0) / 100  }}
          {% endif %}

      - name: "Waterius Hot water m3"
        unique_id: waterius_hot_water_m3
        unit_of_measurement: "m³"
        icon: mdi:water
        state_class: total_increasing
        device_class: water
        availability: >
          {{ not states('sensor.waterius_kolichestvo_impulsov_goriachaia') in ['unavailable', 'unknown'] }}
        state: >
          {% if not states('sensor.waterius_kolichestvo_impulsov_goriachaia') in ['unavailable', 'unknown'] %}
            {{ states('sensor.waterius_kolichestvo_impulsov_goriachaia') | int(0) / 100  }}
          {% endif %}


  utility_meter:
    waterius_cold_water_daily:
      source: sensor.waterius_cold_water_m3
      cycle: daily
    waterius_cold_water_monthly:
      source: sensor.waterius_cold_water_m3
      cycle: monthly
    waterius_hot_water_daily:
      source: sensor.waterius_hot_water_m3
      cycle: daily
    waterius_hot_water_monthly:
      source: sensor.waterius_hot_water_m3
      cycle: monthly
